baseURL = "https://web.northeastern.edu/sunnyland/"
title = "SunnyLand"

theme = "hugo-universal-theme"

languageCode = "en-us"
defaultContentLanguage = "en"

pygmentsUseClassic = true
pygmentsUseClasses = true
pygmentsCodeFences = true

newContentEditor = "nvim"

[params]
# old description - from a poster near the lab
# description = "Professor Zhaohui Sunny Zhou's laboratory (a.k.a. Sunnyland) has an abiding interest in protein modifications, particularly their analysis and chemistry.  In the area of biomedical research, we research crosslinking, methylation, oxidation and asparagine deamidation and others involved in aging, neurological and autoimmune diseases."

  description = "SunnyLand applies protein chemistry, analysis and engineering to biology and medicine.  One program is “Hybrid Modality Engineering of Proteins” — a platform to introduce non-canonical chemical moieties and/or scaffolds into peptides and proteins to confer novel functions otherwise unavailable.  The second is to devise chemo-enzymatic methodologies to characterize protein modifications, such as crosslinking, isoaspartic acid formation (asparagine deamidation) and S-adenosyl-methionine (AdoMet or SAM)-dependent methylations.  In collaboration with biologists and clinicians alike, we also investigate their biological effects, and moreover, as critical attributes in protein pharmaceuticals.  A third program area is the mechanistic studies of and inhibitor design for enzymes with intriguing mechanisms and biomedical significance."
  author = "jfecher"
  defaultKeywords = ["chemistry", "lab", "northeastern", "sunnyland", "sunnylanders"]
  style = "red"
  date_format = ""

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true

[params.features]
    enable = false

[params.testimonials]
    enable = false

[params.see_more]
    enable = true
    icon = "fa fa-envelope"
    title = "See more"
    subtitle = ""
    link_url = "pages/contact"
    link_text = "Contact Us"

[params.clients]
    enable = true
    title = "Current Members"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Recent Posts"
    subtitle = "See more recent posts and publications"
